--  Generated by SDL_parser Ada generator.
--  Source headers: SDL3/SDL_iostream.h
with Interfaces;
with Interfaces.C;
with Interfaces.C.Extensions;
with System;

with SDL.Raw.C_Pointers;
with SDL.Raw.Properties;

package SDL.Raw.IOStream is
   pragma Preelaborate;

   package C renames Interfaces.C;
   package CE renames Interfaces.C.Extensions;

   type IO_Status is
     (
      IO_Status_Ready,
      IO_Status_Error,
      IO_Status_Eof,
      IO_Status_Not_Ready,
      IO_Status_Readonly,
      IO_Status_Writeonly)
   with
     Convention => C,
     Size       => C.int'Size;

   for IO_Status use
     (
      IO_Status_Ready => 0,
      IO_Status_Error => 1,
      IO_Status_Eof => 2,
      IO_Status_Not_Ready => 3,
      IO_Status_Readonly => 4,
      IO_Status_Writeonly => 5);

   type IO_Whence is
     (
      IO_Seek_Set,
      IO_Seek_Cur,
      IO_Seek_End)
   with
     Convention => C,
     Size       => C.int'Size;

   for IO_Whence use
     (
      IO_Seek_Set => 0,
      IO_Seek_Cur => 1,
      IO_Seek_End => 2);

   type Size_Callback is access function
     (Userdata : in System.Address) return Interfaces.Integer_64
   with Convention => C;

   type Seek_Callback is access function
     (Userdata : in System.Address;
      Offset : in Interfaces.Integer_64;
      Whence : in IO_Whence) return Interfaces.Integer_64
   with Convention => C;

   type Read_Callback is access function
     (Userdata : in System.Address;
      Ptr : in System.Address;
      Size : in C.size_t;
      Status : access IO_Status) return C.size_t
   with Convention => C;

   type Write_Callback is access function
     (Userdata : in System.Address;
      Ptr : in System.Address;
      Size : in C.size_t;
      Status : access IO_Status) return C.size_t
   with Convention => C;

   type Flush_Callback is access function
     (Userdata : in System.Address;
      Status : access IO_Status) return CE.bool
   with Convention => C;

   type Close_Callback is access function
     (Userdata : in System.Address) return CE.bool
   with Convention => C;

   type IO_Stream_Interface is record
      Version : Interfaces.Unsigned_32;
      Size : Size_Callback;
      Seek : Seek_Callback;
      Read : Read_Callback;
      Write : Write_Callback;
      Flush : Flush_Callback;
      Close : Close_Callback;
   end record with
     Convention => C;

   type IO_Stream_Object is null record;
   type IO_Stream_Access is access all IO_Stream_Object with
     Convention => C;

   procedure Free (Memory : in System.Address)
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_free";

   function IO_From_File
     (File : in C.char_array;
      Mode : in C.char_array) return SDL.Raw.C_Pointers.IO_Stream_Pointer
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_IOFromFile";

   Iostream_Windows_Handle_Pointer_Property : constant String := "SDL.iostream.windows.handle";

   Iostream_Stdio_File_Pointer_Property : constant String := "SDL.iostream.stdio.file";

   Iostream_File_Descriptor_Number_Property : constant String := "SDL.iostream.file_descriptor";

   Iostream_Android_Aasset_Pointer_Property : constant String := "SDL.iostream.android.aasset";

   function IO_From_Mem
     (Mem : in System.Address;
      Size : in C.size_t) return SDL.Raw.C_Pointers.IO_Stream_Pointer
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_IOFromMem";

   Iostream_Memory_Pointer_Property : constant String := "SDL.iostream.memory.base";

   Iostream_Memory_Size_Number_Property : constant String := "SDL.iostream.memory.size";

   Iostream_Memory_Free_Func_Pointer_Property : constant String := "SDL.iostream.memory.free";

   function IO_From_Const_Mem
     (Mem : in System.Address;
      Size : in C.size_t) return SDL.Raw.C_Pointers.IO_Stream_Pointer
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_IOFromConstMem";

   function IO_From_Dynamic_Mem return SDL.Raw.C_Pointers.IO_Stream_Pointer
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_IOFromDynamicMem";

   Iostream_Dynamic_Memory_Pointer_Property : constant String := "SDL.iostream.dynamic.memory";

   Iostream_Dynamic_Chunksize_Number_Property : constant String := "SDL.iostream.dynamic.chunksize";

   function Open_IO
     (Iface : access constant IO_Stream_Interface;
      Userdata : in System.Address) return SDL.Raw.C_Pointers.IO_Stream_Pointer
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_OpenIO";

   function Close_IO
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_CloseIO";

   function Get_IO_Properties
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer) return SDL.Raw.Properties.ID
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_GetIOProperties";

   function Get_IO_Status
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer) return IO_Status
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_GetIOStatus";

   function Get_IO_Size
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer) return Interfaces.Integer_64
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_GetIOSize";

   function Seek_IO
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Offset : in Interfaces.Integer_64;
      Whence : in IO_Whence) return Interfaces.Integer_64
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_SeekIO";

   function Tell_IO
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer) return Interfaces.Integer_64
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_TellIO";

   function Read_IO
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Ptr : in System.Address;
      Size : in C.size_t) return C.size_t
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadIO";

   function Write_IO
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Ptr : in System.Address;
      Size : in C.size_t) return C.size_t
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteIO";

   function I_Oprintf
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Fmt : in C.char_array) return C.size_t
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_IOprintf";

   function I_Ovprintf
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Fmt : in C.char_array;
      Ap : in System.Address) return C.size_t
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_IOvprintf";

   function Flush_IO
     (Context : in SDL.Raw.C_Pointers.IO_Stream_Pointer) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_FlushIO";

   function Load_File_IO
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Datasize : access C.size_t;
      Closeio : in CE.bool) return System.Address
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_LoadFile_IO";

   function Load_File
     (File : in C.char_array;
      Datasize : access C.size_t) return System.Address
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_LoadFile";

   function Save_File_IO
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Data : in System.Address;
      Datasize : in C.size_t;
      Closeio : in CE.bool) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_SaveFile_IO";

   function Save_File
     (File : in C.char_array;
      Data : in System.Address;
      Datasize : in C.size_t) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_SaveFile";

   function Read_U_8
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_8) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU8";

   function Read_S_8
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_8) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS8";

   function Read_U_16_Le
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU16LE";

   function Read_S_16_Le
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS16LE";

   function Read_U_16_Be
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU16BE";

   function Read_S_16_Be
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS16BE";

   function Read_U_32_Le
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU32LE";

   function Read_S_32_Le
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS32LE";

   function Read_U_32_Be
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU32BE";

   function Read_S_32_Be
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS32BE";

   function Read_U_64_Le
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU64LE";

   function Read_S_64_Le
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS64LE";

   function Read_U_64_Be
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Unsigned_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadU64BE";

   function Read_S_64_Be
     (Src : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : access Interfaces.Integer_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_ReadS64BE";

   function Write_U_8
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_8) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU8";

   function Write_S_8
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_8) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS8";

   function Write_U_16_Le
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU16LE";

   function Write_S_16_Le
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS16LE";

   function Write_U_16_Be
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU16BE";

   function Write_S_16_Be
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_16) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS16BE";

   function Write_U_32_Le
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU32LE";

   function Write_S_32_Le
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS32LE";

   function Write_U_32_Be
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU32BE";

   function Write_S_32_Be
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_32) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS32BE";

   function Write_U_64_Le
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU64LE";

   function Write_S_64_Le
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS64LE";

   function Write_U_64_Be
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Unsigned_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteU64BE";

   function Write_S_64_Be
     (Dst : in SDL.Raw.C_Pointers.IO_Stream_Pointer;
      Value : in Interfaces.Integer_64) return CE.bool
   with
     Import        => True,
     Convention    => C,
     External_Name => "SDL_WriteS64BE";
end SDL.Raw.IOStream;
